CREATE TABLE [Sheet1tbl_LocationsUpdate] (
  [ID] AUTOINCREMENT CONSTRAINT [ID] PRIMARY KEY  UNIQUE  NOT NULL ,
  [Site_ID] VARCHAR (255),
  [GIS_Location_ID] VARCHAR (255),
  [Meta_MID] VARCHAR (255),
  [UTM_X_Coord] DOUBLE ,
  [UTM_Y_Coord] DOUBLE ,
  [Coord_Units] VARCHAR (255),
  [Coord_System] VARCHAR (255),
  [UTM_Zone] VARCHAR (255),
  [Datum] VARCHAR (255),
  [Est_H_Error] VARCHAR (255),
  [Accuracy_Notes] VARCHAR (255),
  [Unit_Code] VARCHAR (255),
  [Sub_Unit_Code] VARCHAR (255),
  [Loc_Code] VARCHAR (255),
  [Loc_Name] VARCHAR (255),
  [Loc_Type] VARCHAR (255),
  [Updated_Date] VARCHAR (255),
  [Loc_Notes] VARCHAR (255),
  [Logger] BIT ,
  [Lat_DD] DOUBLE ,
  [Long_DD] DOUBLE ,
  [Loc_Description] LONGTEXT ,
  [Travel_Directions] VARCHAR (255),
  [HUC] VARCHAR (255),
  [County] VARCHAR (255),
  [State] VARCHAR (255)
)
