dbMemo "SQL" ="SELECT Format([Start_Date],\"yyyymmdd\") & \"_\" & [StationID] & \"_\" & [Samp_I"
    "ncrement] AS ActivityID, Format([Loc_Code]) AS StationID, tbl_Events.Start_Date "
    "AS [Visit Start Date], Format([Start_Time]) AS [Visit Start Time], IIf(Month([St"
    "art_Date])>3 And Month([Start_Date])<11,\"EDT\",\"EST\") AS Time_Zone, tbl_Core_"
    "Water_Data.Samp_Increment, IIf([Sampleability]=\"0\",\"*Absent\",IIf([Sampleabil"
    "ity]=\"1\",\"*Not Reported\",\015\012IIf([Sampleability]=\"2\" Or [pH]=\"*\",\"*"
    "Not Reported\",Round([pH],3)))) AS pH1, IIf([Sampleability]=\"0\",\"*Absent\",\015"
    "\012IIf([Sampleability]=\"1\",\"*Not Reported\",\015\012IIf([Sampleability]=\"2\""
    " Or [Percent_DO]=\"*\",\"*Not Reported\",Round([Percent_DO],3)))) AS [DO(%)], II"
    "f([Sampleability]=\"0\",\"*Absent\",\015\012IIf([Sampleability]=\"1\",\"*Not Rep"
    "orted\",\015\012IIf([Sampleability]=\"2\" Or [DO]=\"*\",\"*Not Reported\",Round("
    "[DO],3)))) AS [DO(mg/L)], IIf([Sampleability]=\"0\",\"*Absent\",IIf([Sampleabili"
    "ty]=\"1\",\"*Not Reported\",\015\012IIf([Sampleability]=\"2\" Or [Water_Temp]=\""
    "*\",\"*Not Reported\",\015\012Round([Water_Temp],2)))) AS [Water Temperature], I"
    "If([Sampleability]=\"0\",\"*Absent\",\015\012IIf([Sampleability]=\"1\",\"*Not Re"
    "ported\",\015\012IIf([Sampleability]=\"2\" Or [Spec_Conductance]=\"*\",\"*Not Re"
    "ported\",Round([Spec_Conductance],3)))) AS [Specific Conductance], IIf([Sampleab"
    "ility]=\"0\",\"*Absent\",\015\012IIf([Sampleability]=\"1\",\"*Not Reported\",\015"
    "\012IIf([Sampleability]=\"2\" Or [Salinity]=\"*\",\"*Not Reported\",Round([Salin"
    "ity],3)))) AS Salinity1, IIf([Sampleability]=\"0\",\"*Absent\",\015\012IIf([Samp"
    "leability]=\"1\",\"*Not Reported\",\015\012IIf([Sampleability]=\"2\" Or [Conduct"
    "ivity]=\"*\",\"*Not Reported\",Round([Conductivity],3)))) AS Conductivity1, tbl_"
    "Core_Water_Data.TDS, tbl_Event_Details.Event_Notes AS [Visit Comment]\015\012FRO"
    "M (((((tbl_Locations INNER JOIN tbl_Events ON tbl_Locations.Location_ID = tbl_Ev"
    "ents.Location_ID) LEFT JOIN qry_Export_ANC ON tbl_Events.Event_ID = qry_Export_A"
    "NC.Event_ID) LEFT JOIN qry_Nutrients ON tbl_Events.Event_ID = qry_Nutrients.Even"
    "t_ID) LEFT JOIN tbl_Event_Details ON tbl_Events.Event_ID = tbl_Event_Details.Eve"
    "nt_ID) INNER JOIN tbl_Core_Water_Data ON tbl_Events.Event_ID = tbl_Core_Water_Da"
    "ta.Event_ID) LEFT JOIN tbl_Stream_Condition ON tbl_Events.Event_ID = tbl_Stream_"
    "Condition.Event_ID\015\012WHERE tbl_Events.Start_Date BETWEEN [Forms]![frm_Expor"
    "t]![cbo_Export_Start_Date].[Value] AND [Forms]![frm_Export]![cbo_Export_End_Date"
    "].[Value];\015\012"
dbMemo "Connect" =""
dbBoolean "ReturnsRecords" ="-1"
dbInteger "ODBCTimeout" ="60"
dbBoolean "OrderByOn" ="0"
dbByte "Orientation" ="0"
dbByte "DefaultView" ="2"
dbBoolean "FilterOnLoad" ="0"
dbBoolean "OrderByOnLoad" ="-1"
Begin
End
